{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "checkout.configMapName" . }}
data:
  {{- if .Values.redis.create }}
  REDIS_URL: redis://checkout-redis:6379
  {{- end }}
{{- end }}
