version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/src/cart"
    schedule:
      interval: "monthly"
  - package-ecosystem: "maven"
    directory: "/src/orders"
    schedule:
      interval: "monthly"
