version: '2'

services:
  payment:
    build:
      context: .
      dockerfile: ../../images/go/Dockerfile
      args:
        MAIN_PATH: cmd/paymentsvc/main.go
    image: microservices-demo/payment
    hostname: payment
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    ports:
      - "8082:8080"
