#@ load("@ytt:data", "data")

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: front-end
  namespace: #@ data.values.namespace
  labels:
    name: front-end
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: ui
          servicePort: 80