stages:
    - "infrastructure"
    - "build"
    - "deploy-to-dev"
    - "deploy-to-prod"

test_artifact:
    stage: infrastructure
    script:
        - cp $CONFIG /builds/Janortop5/capstone-microservices-demo-watchn/config
    artifacts:
      paths:
      - /builds/Janortop5/capstone-microservices-demo-watchn/config
      expire_in: 1 week

did_it_workk:
    stage: build
    image: ubuntu:22.10
    script:
        - cat /builds/Janortop5/capstone-microservices-demo-watchn/config

deploy_to_dev:
    stage: deploy-to-dev
    image:
        name: dtzar/helm-kubectl:latest
        entrypoint: ['']
    script:
        - kubectl
        - helm
        - helmfile

    # script:
    #     - export KUBECONFIG=/builds/Janortop5/capstone-microservices-demo-watchn/config
    #     - kubectl get nodes
