stages:
    - "infrastructure"
    - "build"
    - "deploy-to-dev"
    - "deploy-to-prod"

test_artifact:
    stage: infrastructure
    script:
        - echo "is artifact test successful?" >> /builds/Janortop5/capstone-microservices-demo-watchn/test_artifact.txt
    artifacts:
      paths:
      - /builds/Janortop5/capstone-microservices-demo-watchn/test_artifact.txt
      expire_in: 1 week

did_it_workk:
    stage: build
    image: ubuntu:22.10
    script:
        - cat /builds/Janortop5/capstone-microservices-demo-watchn/test_artifact.txt

