#@ load("@ytt:data", "data")

#@ if not len(data.values.imageTag) > 0:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: #@ data.values.user.image
  path: #@ data.values.user.imagePath

#@ if/end len(data.values.pushRepo) > 0:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: #@ data.values.user.image
  newImage: #@ data.values.pushRepo + '/shop-user'
#@ end

#@ if/end len(data.values.imageTag) > 0:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageOverrides
overrides:
- image: #@ data.values.user.image
  newImage: #@ 'docker.io/niallthomson/shop-user:' + data.values.imageTag
  preresolved: true