version: '2'

services:
  checkout:
    build:
      context: .
      dockerfile: ../../images/nodejs/Dockerfile
    image: microservices-demo/checkout
    hostname: checkout
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - REDIS_URL=redis://checkout-redis:6379
    ports:
      - "8085:8080"
  checkout-redis:
    image: redis:6.0-alpine
    hostname: checkout-redis
    restart: always
    ports:
      - "6379:6379"