management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: ${port:8080}
  codec.max-in-memory-size: 10MB

endpoints:
  catalog: http://localhost:8081
  carts: http://localhost:8082
  orders: http://localhost:8083