#@ load("@ytt:data", "data")

#@ if data.values.ui.hpa.enabled:
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ui
  namespace: #@ data.values.namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ui
  minReplicas: #@ data.values.ui.hpa.minReplicas
  maxReplicas: #@ data.values.ui.hpa.maxReplicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
#@ end