#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    name: ui
  namespace: #@ data.values.namespace
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 180
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  #@ if/end not data.values.hpa.enabled:
  replicas: #@ data.values.ui.replicas
  selector:
    matchLabels:
      name: ui
  template:
    metadata:
      labels:
        name: ui
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - ui
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
      containers:
      - name: ui
        image: #@ data.values.ui.image.build.id
        ports:
          - name: http
            containerPort: 8080
        env:
          - name: JAVA_OPTS
            value: -Xms64m -Xmx512m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
          - name: ENDPOINTS_CATALOG
            value: http://catalogue:8080
          - name: ENDPOINTS_CARTS
            value: http://carts:8080
          - name: ENDPOINTS_ORDERS
            value: http://orders:8080
        #@ if/end len(data.values.ui.configMap.name) > 0:
        envFrom:
        - configMapRef:
            name: #@ data.values.ui.configMap.name
        resources:
          requests:
            memory: "768Mi"
          limits:
            memory: "768Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory

#@ if data.values.services.enabled:
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    name: ui
  namespace: #@ data.values.namespace
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
  selector:
    name: ui
#@ end