#@ load("@ytt:data", "data")

---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: #@ data.values.orders.image
  path: #@ data.values.orders.imagePath
  docker:
    build:
      file: #@ data.values.imagePath + '/java/Dockerfile'
      rawOptions: ["--build-arg", "JAR_PATH=target/orders.jar"]
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: #@ data.values.orders.image
  newImage: docker.io/niallthomson/shop-orders