#@ load("@ytt:data", "data")

#@ if not len(data.values.imageTag) > 0:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: #@ data.values.orders.image
  path: #@ data.values.orders.imagePath
  docker:
    build:
      file: #@ data.values.imagePath + '/java11/Dockerfile'
      rawOptions: ["--build-arg", "JAR_PATH=target/orders-0.0.1-SNAPSHOT.jar"]

#@ if/end len(data.values.pushRepo) > 0:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: #@ data.values.orders.image
  newImage: #@ data.values.pushRepo + '/shop-orders'
#@ end

#@ if/end len(data.values.imageTag) > 0:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageOverrides
overrides:
- image: #@ data.values.orders.image
  newImage: #@ 'docker.io/niallthomson/shop-orders:' + data.values.imageTag
  preresolved: true