#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  labels:
    name: orders-db
  namespace: #@ data.values.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orders-db
  template:
    metadata:
      labels:
        name: orders-db
    spec:
      containers:
      - name: orders-db
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: my-secret-pw
          - name: MYSQL_DATABASE
            value: orders
          - name: MYSQL_USER
            value: orders_user
          - name: MYSQL_PASSWORD
            value: default_password
        ports:
        - name: mysql
          containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  labels:
    name: orders-db
  namespace: #@ data.values.namespace
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: orders-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    name: orders
  namespace: #@ data.values.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orders
  template:
    metadata:
      labels:
        name: orders
        fargate: "true"
    spec:
      containers:
      - name: orders
        image: #@ data.values.orders.image
        ports:
         - containerPort: 8080
        env:
          - name: JAVA_OPTS
            value: -Xms128m -Xmx512m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
          - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
            value: true
          - name: SPRING_PROFILES_ACTIVE
            value: mysql
          - name: SPRING_DATASOURCE_WRITER_URL
            value: jdbc:mysql://orders-db:3306/orders
          - name: SPRING_DATASOURCE_WRITER_USERNAME
            value: orders_user
          - name: SPRING_DATASOURCE_WRITER_PASSWORD
            value: default_password
          - name: SPRING_DATASOURCE_READER_URL
            value: jdbc:mysql://orders-db:3306/orders
          - name: SPRING_DATASOURCE_READER_USERNAME
            value: orders_user
          - name: SPRING_DATASOURCE_READER_PASSWORD
            value: default_password
        resources:
          requests:
            memory: "512Mi"
          limits:
            memory: "512Mi"
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    name: orders
  namespace: #@ data.values.namespace
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: orders