#@ load("@ytt:data", "data")


apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    name: orders
  namespace: #@ data.values.namespace
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 180
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  #@ if/end not data.values.orders.hpa.enabled:
  replicas: #@ data.values.orders.replicas
  selector:
    matchLabels:
      name: orders
  template:
    metadata:
      labels:
        name: orders
    spec:
      containers:
      - name: orders
        image: #@ data.values.orders.image.build.id
        ports:
         - name: http
           containerPort: 8080
        env:
          - name: JAVA_OPTS
            value: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
          - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
            value: "true"
          - name: SPRING_PROFILES_ACTIVE
            value: mysql
        envFrom:
          - configMapRef:
              name: #@ data.values.orders.configMap.name
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "1Gi"
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 3
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      securityContext:
        readOnlyRootFilesystem: #@ data.values.orders.securityContext.readOnlyRootFilesystem

#@ if/end data.values.orders.configMap.create:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ data.values.orders.configMap.name
  namespace: #@ data.values.namespace

#@ if/end data.values.orders.service.create:
---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.orders.service.name
  labels:
    name: #@ data.values.orders.service.name
  namespace: #@ data.values.namespace
spec:
  ports:
  - port: 8080
    targetPort: http
  selector:
    name: orders