#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:overlay", "overlay")

#@ if data.values.includeServices:
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.orders.services.mysqlWriter.secret
  namespace: #@ data.values.namespace
data:
  url: #@ base64.encode("jdbc:mysql://orders-db:3306/orders")
  username: #@ base64.encode("orders_user")
  password: #@ base64.encode("default_password")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.orders.services.mysqlReader.secret
  namespace: #@ data.values.namespace
data:
  url: #@ base64.encode("jdbc:mysql://orders-db:3306/orders")
  username: #@ base64.encode("orders_user")
  password: #@ base64.encode("default_password")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  labels:
    name: orders-db
  namespace: #@ data.values.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orders-db
  template:
    metadata:
      labels:
        name: orders-db
    spec:
      containers:
      - name: orders-db
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: my-secret-pw
          - name: MYSQL_DATABASE
            value: orders
          - name: MYSQL_USER
            value: orders_user
          - name: MYSQL_PASSWORD
            value: default_password
        ports:
        - name: mysql
          containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  labels:
    name: orders-db
  namespace: #@ data.values.namespace
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: orders-db
#@ end

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "orders"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: orders
        #@overlay/match-child-defaults missing_ok=True
        env:
        #@overlay/match by="name"
        - name: SPRING_DATASOURCE_WRITER_URL
          valueFrom:
            secretKeyRef:
              name: #@ data.values.orders.services.mysqlWriter.secret
              key: url
        #@overlay/match by="name"
        - name: SPRING_DATASOURCE_WRITER_USERNAME
          valueFrom:
            secretKeyRef:
              name: #@ data.values.orders.services.mysqlWriter.secret
              key: username
        #@overlay/match by="name"
        - name: SPRING_DATASOURCE_WRITER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: #@ data.values.orders.services.mysqlWriter.secret
              key: password
        #@overlay/match by="name"
        - name: SPRING_DATASOURCE_READER_URL
          valueFrom:
            secretKeyRef:
              name: #@ data.values.orders.services.mysqlReader.secret
              key: url
        #@overlay/match by="name"
        - name: SPRING_DATASOURCE_READER_USERNAME
          valueFrom:
            secretKeyRef:
              name: #@ data.values.orders.services.mysqlReader.secret
              key: username
        #@overlay/match by="name"
        - name: SPRING_DATASOURCE_READER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: #@ data.values.orders.services.mysqlReader.secret
              key: password