#@data/values
---
#@overlay/match missing_ok=True
orders:
  image: 
    name: watchn-orders
    build:
      id: watchn-orders
      path: .

  replicas: 1

  mysql:
    create: true
    writer:
      secret: orders-writer-db
    reader:
      secret: orders-reader-db

  service:
    create: true
    name: orders

  configMap:
    name: orders
    create: true

  metrics:
    enabled: false

  hpa:
    enabled: false
    minReplicas: 2
    maxReplicas: 4

  securityContext:
    readOnlyRootFilesystem: true

  resources:
    memory: 512Mi