#@data/values
---
#@overlay/match missing_ok=True
orders:
  image: watchn-shop-orders
  imagePath: .
  services:
    mysqlWriter:
      secret: orders-writer-db
    mysqlReader:
      secret: orders-reader-db