#@data/values
---
#@overlay/match missing_ok=True
orders:
  image: 
    name: watchn-orders
    build:
      id: watchn-orders
      path: .

  replicas: 1

  mysql:
    create: true
    writer:
      secret: orders-writer-db
    reader:
      secret: orders-reader-db

  service:
    create: true
    name: orders

  configMap:
    name: orders
    create: true

  metrics:
    enabled: false
    service:
      port: 8080
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"

  hpa:
    enabled: false
    minReplicas: 2
    maxReplicas: 4

  securityContext:
    readOnlyRootFilesystem: true