basePath: /customers
definitions:
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  model.Address:
    properties:
      city:
        type: string
      country:
        type: string
      number:
        type: string
      postcode:
        type: string
      street:
        type: string
    type: object
  model.Card:
    properties:
      ccv:
        type: string
      expires:
        type: string
      longNum:
        type: string
    type: object
  model.User:
    properties:
      addresses:
        items:
          $ref: '#/definitions/model.Address'
        type: array
      cards:
        items:
          $ref: '#/definitions/model.Card'
        type: array
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This API stores user data
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: User API
  version: "1.0"
paths:
  /customers/{id}:
    get:
      consumes:
      - application/json
      description: Get customer addresses
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Address'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get customer addresses
      tags:
      - customers
  /customers/{id}/cards:
    get:
      consumes:
      - application/json
      description: Get customer cards
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Card'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get customer cards
      tags:
      - customers
swagger: "2.0"
