#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:overlay", "overlay")

#@ if data.values.cart.persistence == "dynamodb":
#@overlay/match by=overlay.subset({"kind": "ConfigMap", "metadata": {"name": "carts"}})
---
#@overlay/match-child-defaults missing_ok=True
data:
  CARTS_DYNAMODB_TABLENAME: #@ data.values.cart.dynamodb.tableName
  CARTS_DYNAMODB_CREATETABLE: #@ str(data.values.cart.dynamodb.createTable).lower()

#@ if data.values.cart.dynamodb.create:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-db
  labels:
    name: carts-db
  namespace: #@ data.values.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      name: carts-db
  template:
    metadata:
      labels:
        name: carts-db
    spec:
      containers:
      - name: carts-db
        image: amazon/dynamodb-local:1.13.1
        ports:
        - name: dynamodb
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: carts-db
  labels:
    name: carts-db
  namespace: #@ data.values.namespace
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    name: carts-db

#@overlay/match by=overlay.subset({"kind": "ConfigMap", "metadata": {"name": "carts"}})
---
#@overlay/match-child-defaults missing_ok=True
data:
  CARTS_DYNAMODB_CREATETABLE: "true"
  AWS_ACCESS_KEY_ID: key
  AWS_SECRET_ACCESS_KEY: secret
  CARTS_DYNAMODB_ENDPOINT: http://carts-db:8000
#@ end

#@ end