#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  labels:
    name: carts
  namespace: #@ data.values.namespace
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 180
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  #@ if/end not data.values.cart.hpa.enabled:
  replicas: #@ data.values.cart.replicas
  selector:
    matchLabels:
      name: carts
  template:
    metadata:
      labels:
        name: carts
    spec:
      containers:
      - name: carts
        image: #@ data.values.cart.image.build.id
        ports:
         - name: http
           containerPort: 8080
        env:
          - name: JAVA_OPTS
            value: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
        envFrom:
          - configMapRef:
              name: #@ data.values.cart.configMap.name
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 3
        securityContext:
          readOnlyRootFilesystem: #@ data.values.cart.securityContext.readOnlyRootFilesystem
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      serviceAccountName: #@ data.values.cart.serviceAccount.name
      automountServiceAccountToken: true
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory

#@ if/end data.values.cart.configMap.create:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ data.values.cart.configMap.name
  namespace: #@ data.values.namespace
data:
  SPRING_PROFILES_ACTIVE: dynamodb

#@ if/end data.values.cart.serviceAccount.create:
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: #@ data.values.cart.serviceAccount.name
  namespace: #@ data.values.namespace
  #@ if/end data.values.cart.serviceAccount.annotations:
  annotations: #@ data.values.cart.serviceAccount.annotations

#@ if/end data.values.cart.service.create:
---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.cart.service.name
  labels:
    name: #@ data.values.cart.service.name
  namespace: #@ data.values.namespace
spec:
  ports:
  - port: 8080
    targetPort: http
  selector:
    name: carts