#@data/values
---
#@overlay/match missing_ok=True
cart:
  image:
    name: watchn-cart
    build:
      id: watchn-cart
      path: .

  replicas: 1

  configMap:
    create: true
    name: carts

  persistence: dynamodb

  serviceAccount:
    name: carts
    create: true
    annotations: {}

  service:
    create: true
    name: carts

  metrics:
    enabled: false

  hpa:
    enabled: false
    minReplicas: 3
    maxReplicas: 6

  securityContext:
    readOnlyRootFilesystem: true

  dynamodb:
    tableName: Items
    createTable: false
    create: true