#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    name: catalogue
  namespace: #@ data.values.namespace
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 180
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  replicas: #@ data.values.catalog.replicas
  selector:
    matchLabels:
      name: catalogue
  template:
    metadata:
      labels:
        name: catalogue
        fargate: "true"
    spec:
      containers:
      - name: catalogue
        image: #@ data.values.catalog.image.build.id
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "256Mi"
        #@ if/end len(data.values.catalog.configMap.name) > 0:
        envFrom:
        - configMapRef:
            name: #@ data.values.catalog.configMap.name
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    name: catalogue
  namespace: #@ data.values.namespace
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: catalogue