#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    name: catalogue
  namespace: #@ data.values.namespace
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 180
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  #@ if/end not data.values.catalog.hpa.enabled:
  replicas: #@ data.values.catalog.replicas
  selector:
    matchLabels:
      name: catalogue
  template:
    metadata:
      labels:
        name: catalogue
    spec:
      containers:
      - name: catalogue
        image: #@ data.values.catalog.image.build.id
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: #@ data.values.catalog.configMap.name

#@ if/end data.values.catalog.configMap.create:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ data.values.catalog.configMap.name
  namespace: #@ data.values.namespace

#@ if/end data.values.catalog.service.create:
---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.catalog.service.name
  labels:
    name: #@ data.values.catalog.service.name
  namespace: #@ data.values.namespace
spec:
  ports:
  - port: 8080
    targetPort: http
  selector:
    name: catalogue