#@data/values
---
#@overlay/match missing_ok=True
catalog:
  image: watchn-catalog
  imagePath: .
  replicas: 1
  services:
    mysqlWriter:
      secret: catalog-writer-db
    mysqlReader:
      secret: catalog-reader-db