version: '3.4'

networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:latest
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "80:3000"
    cap_add:
      - CAP_NET_BIND_SERVICE
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=${WATCHN_K6_OUT}
      - WATCHN_BASE_URL=${WATCHN_BASE_URL}
      - WATCHN_REGION=${WATCHN_REGION}
      - WATCHN_TARGET=${WATCHN_TARGET}
    volumes:
      - ./js:/js