version: '2'

services:
    catalogue:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          MAIN_PATH: cmd/cataloguesvc/main.go
      image: microservices-demo/catalogue
      hostname: catalogue
      depends_on:
      - catalogue-db
      restart: always
      cap_drop:
        - all
      read_only: true
      environment:
        - reschedule=on-node-failure
      ports:
        - "8080:8080"
    catalogue-db:
      build:
        context: ./docker/catalogue-db/
      image: weaveworksdemos/catalogue-db
      hostname: catalogue-db
      restart: always
      environment:
        - reschedule=on-node-failure
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
        - MYSQL_DATABASE=socksdb
