repositories:
# Stable repo of official helm charts
- name: "stable"
  url: "https://kubernetes-charts.storage.googleapis.com"

releases:
- name: "activemq"
  namespace: "watchn"
  chart: ./activemq/chart
  wait: true

- name: "catalog"
  namespace: "watchn"
  chart: ../../src/catalog/chart
  wait: true

- name: "carts"
  namespace: "watchn"
  chart: ../../src/cart/chart
  wait: true

- name: "orders"
  namespace: "watchn"
  chart: ../../src/orders/chart
  wait: true
  values:
    - messaging:
        activemq: 
          brokerUrl: "tcp://activemq-0.activemq:61616"

- name: "checkout"
  namespace: "watchn"
  chart: ../../src/checkout/chart
  wait: true

- name: "assets"
  namespace: "watchn"
  chart: ../../src/assets/chart
  wait: true

- name: "ui"
  namespace: "watchn"
  chart: ../../src/ui/chart
  wait: true
  timeout: 600
  values:
    - service:
        type: LoadBalancer