version: '2'

services:
  ui:
    ports:
    - 80:8080
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
      - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
      - ENDPOINTS_CATALOG=http://catalog:8080
      - ENDPOINTS_CARTS=http://carts:8080
      - ENDPOINTS_ORDERS=http://orders:8080
      - ENDPOINTS_ASSETS=http://assets:8080
    hostname: ui
    build:
      context: ../../src/ui
      dockerfile: ../../images/java11/Dockerfile
      args:
        JAR_PATH: target/ui-0.0.1-SNAPSHOT.jar
    restart: always
  catalog:
    hostname: catalog
    build:
      context: ../../src/catalog
      dockerfile: Dockerfile
    restart: always
  catalog-db:
    image: mysql:5.7
    hostname: catalog-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=watchndb
      - MYSQL_USER=catalog_user
      - MYSQL_PASSWORD=default_password
  carts:
    hostname: carts
    build:
      context: ../../src/cart
      dockerfile: ../../images/java11/Dockerfile
      args:
        JAR_PATH: target/carts-0.0.1-SNAPSHOT.jar
    restart: always
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
      - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
      - SPRING_PROFILES_ACTIVE=dynamodb
      - CARTS_DYNAMODB_ENDPOINT=http://carts-db:8000
      - CARTS_DYNAMODB_CREATETABLE=true
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
  carts-db:
    image: amazon/dynamodb-local:1.13.1
    hostname: carts-db
    restart: always
  orders:
    hostname: orders
    build:
      context: ../../src/orders
      dockerfile: ../../images/java11/Dockerfile
      args:
        JAR_PATH: target/orders-0.0.1-SNAPSHOT.jar
    restart: always
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
      - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_WRITER_URL=jdbc:mysql://orders-db:3306/orders
      - SPRING_DATASOURCE_WRITER_USERNAME=orders_user
      - SPRING_DATASOURCE_WRITER_PASSWORD=default_password
      - SPRING_DATASOURCE_READER_URL=jdbc:mysql://orders-db:3306/orders
      - SPRING_DATASOURCE_READER_USERNAME=orders_user
      - SPRING_DATASOURCE_READER_PASSWORD=default_password
  orders-db:
    image: mysql:5.7
    hostname: orders-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=orders
      - MYSQL_USER=orders_user
      - MYSQL_PASSWORD=default_password
  assets:
    hostname: assets
    build:
      context: ../../src/assets
      dockerfile: Dockerfile
    restart: always