---
services:
  carts:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    environment:
    - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
    - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
    - SPRING_PROFILES_ACTIVE=dynamodb
    - AMAZON_DYNAMODB_endpoint=http://carts-db:8000
    - AWS_ACCESS_KEY_ID=key
    - AWS_SECRET_ACCESS_KEY=secret
    hostname: carts
    image: docker.io/niallthomson/shop-carts:0.0.2
    read_only: true
    restart: always
    tmpfs:
    - /tmp:rw,noexec,nosuid
  carts-db:
    cap_add:
    - CHOWN
    - SETGID
    - SETUID
    cap_drop:
    - all
    environment:
    - reschedule=on-node-failure
    hostname: carts-db
    image: index.docker.io/amazon/dynamodb-local@sha256:648d5f0a5eb96b789040dcc56256a5b16a4097722327e7c8e1598daaa2fde385
    read_only: true
    restart: always
    tmpfs:
    - /tmp:rw,noexec,nosuid
  catalog-db:
    environment:
    - reschedule=on-node-failure
    - MYSQL_ROOT_PASSWORD=my-secret-pw
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_DATABASE=watchndb
    - MYSQL_USER=catalog_user
    - MYSQL_PASSWORD=default_password
    hostname: catalog-db
    image: index.docker.io/library/mysql@sha256:32f9d9a069f7a735e28fd44ea944d53c61f990ba71460c5c183e610854ca4854
    restart: always
  catalogue:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    hostname: catalogue
    image: docker.io/niallthomson/shop-catalog:0.0.2
    read_only: true
    restart: always
  orders:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    environment:
    - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
    hostname: orders
    image: docker.io/niallthomson/shop-orders:0.0.2
    read_only: true
    restart: always
    tmpfs:
    - /tmp:rw,noexec,nosuid
  orders-db:
    cap_add:
    - CHOWN
    - SETGID
    - SETUID
    - NET_BIND_SERVICE
    cap_drop:
    - all
    hostname: orders-db
    image: index.docker.io/library/mongo@sha256:d314f7eca9d3f825d091b77c40d2f3c9d6fff4de88dde2962527353476f107ba
    read_only: true
    restart: always
    tmpfs:
    - /tmp:rw,noexec,nosuid
  queue-master:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    hostname: queue-master
    image: index.docker.io/weaveworksdemos/queue-master@sha256:6292d3095f4c7aeed8d863527f8ef6d7a75d3128f20fc61e57f398c100142712
    read_only: true
    restart: always
    tmpfs:
    - /tmp:rw,noexec,nosuid
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  rabbitmq:
    cap_add:
    - CHOWN
    - SETGID
    - SETUID
    - DAC_OVERRIDE
    - NET_BIND_SERVICE
    cap_drop:
    - all
    hostname: rabbitmq
    image: index.docker.io/library/rabbitmq@sha256:a9f4923559bbcd00b93b02e61615aef5eb6f1d1c98db51053bab0fa6b680db26
    read_only: true
    restart: always
  shipping:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    environment:
    - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
    hostname: shipping
    image: index.docker.io/weaveworksdemos/shipping@sha256:983305c948fded487f4a4acdeab5f898e89d577b4bc1ca3de7750076469ccad4
    read_only: true
    restart: always
    tmpfs:
    - /tmp:rw,noexec,nosuid
  ui:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    environment:
    - JAVA_OPTS=-Xms64m -Xmx256m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
    - ENDPOINTS_CATALOG=http://catalogue:8080
    - ENDPOINTS_CARTS=http://carts:8080
    hostname: ui
    image: docker.io/niallthomson/shop-ui:0.0.2
    ports:
    - 80:8080
    read_only: true
    restart: always
version: "2"
