name: Assets CI

on:
  push:
    branches:
    - master
    paths:
    - 'src/assets/**'
  pull_request:
    branches:
    - master
    paths:
    - 'src/assets/**'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run
      run: |
        src/assets/scripts/ci.sh
    