name: Carts CI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run
      run: |
        src/cart/scripts/ci.sh
    