name: Carts CI

on:
  push:
    branches:
    - master
    paths:
    - 'src/cart/**'
  pull_request:
    branches:
    - master
    paths:
    - 'src/cart/**'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run
      env:
        AWS_ACCESS_KEY_ID: dummy
        AWS_SECRET_ACCESS_KEY: dummy
        MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
      run: |
        src/cart/scripts/ci.sh
    - name: Docker Compose
      run: |
        (cd src/cart && docker-compose up -d)