name: Checkout CI

on:
  push:
    branches:
    - master
    paths:
    - 'src/checkout/**'
  pull_request:
    branches:
    - master
    paths:
    - 'src/checkout/**'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Run
      run: |
        src/checkout/scripts/ci.sh
    