name: Kind CI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build images
      env:
        REPO: watchn
      run: |
        TAG=${GITHUB_SHA} scripts/build-all.sh
    - uses: engineerd/setup-kind@v0.5.0
    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v0.7.0
    - name: Deploy
      run: |
        cd deploy/kubernetes && IMAGE_TAG=${GITHUB_SHA} helmfile apply
        kubectl get pod -A
    