name: Kind CI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build images
      env:
        REPO: watchn
      run: |
        TAG=${GITHUB_SHA} scripts/build-all.sh
    - uses: engineerd/setup-kind@v0.5.0
    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v0.7.0
    - name: Deploy
      env:
        UI_SERVICE_TYPE: NodePort
      run: |
        kind load docker-image watchn/watchn-assets:${GITHUB_SHA}
        kind load docker-image watchn/watchn-cart:${GITHUB_SHA}
        kind load docker-image watchn/watchn-catalog:${GITHUB_SHA}
        kind load docker-image watchn/watchn-checkout:${GITHUB_SHA}
        kind load docker-image watchn/watchn-orders:${GITHUB_SHA}
        kind load docker-image watchn/watchn-ui:${GITHUB_SHA}

        cd deploy/kubernetes && IMAGE_TAG=${GITHUB_SHA} helmfile apply --suppress-diff

        sleep 20

        kubectl get pod -A
        kubectl get svc -A

        node_port=$(kubectl -n watchn get svc ui -o jsonpath='{.spec.ports[0].nodePort}')

        curl localhost:${node_port}/home
    