name: UI CI

on:
  push:
    branches:
    - master
    paths:
    - 'src/ui/**'
  pull_request:
    branches:
    - master
    paths:
    - 'src/ui/**'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run
      env:
        MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
      run: |
        src/ui/scripts/ci.sh
    - name: Docker Compose
      run: |
        (cd src/ui && docker-compose up -d)
    